apiVersion: v1
kind: Service
metadata:
  name: surveyform-vue-service
spec:
  selector:
    app: surveyform-vue
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
