#Athiksha Venkannagari - G01461169
#Arsitha Sathu - G01445215
#Ramyasahithya Magani - G01425752
#Prasad Reddy Mandha - G01454689
#SaichinmayeeYanamadala - G01459318
#LikhithNattuva - G0144733
#Priya Dharshini Allapuram - G01457911
#Sreshta Kosaraju - G01460468

# service.yaml file has surveyform-vue-service that exposes the application with a NodePort type,
# allowing external access to the application on port 30080.
# It routes traffic to pods labeled with app:surveyform-vue

apiVersion: v1
kind: Service
metadata:
  name: surveyform-vue-service
spec:
  selector:
    app: surveyform-vue
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
